/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openscience_jchempaint_OsxClipboard */

#ifndef _Included_org_openscience_jchempaint_OsxClipboard
#define _Included_org_openscience_jchempaint_OsxClipboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openscience_jchempaint_OsxClipboard
 * Method:    setClipboard
 * Signature: ([BILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openscience_jchempaint_OsxClipboard_setClipboard
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif